FROM ubuntu:bionic

apt-get update
apt-get install curl -y
apt-get install git -y
apt-get install vim -y
apt-get install zip -y
apt-get install unzip -y
apt-get install wget -y
apt-get install openjdk-8-jdk -y
apt-get install python3.7 -y
apt-get install python3-pip

wget http://apache.tt.co.kr/spark/spark-2.4.5/spark-2.4.5-bin-hadoop2.7.tgz
tar -xvzf ~/spark-2.4.5-bin-hadoop2.7.tgz
# mv ~/spark-2.4.5-bin-hadoop2.7.tgz /opt/spark
mv ~/spark-2.4.5-bin-hadoop2.7 /opt/spark

wget http://www.scala-lang.org/files/archive/scala-2.11.8.deb
dpkg -i scala-2.11.8.deb
apt-get install scala -y

wget https://bintray.com/artifact/download/sbt/debian/sbt-1.3.5.deb
dpkg -i sbt-1.3.5.deb
apt-get install sbt -y

wget https://sdk-for-java.amazonwebservices.com/latest/aws-java-sdk.zip
unzip aws-java-sdk.zip

echo 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64' >> ~/.bashrc
echo 'export PATH=$JAVA_HOME/bin:$PATH' >> ~/.bashrc

# SPARK Settings
echo 'export SPARK_HOME=/opt/spark' >> ~/.bashrc
echo 'export PATH=$SPARK_HOME/bin:$PATH' >> ~/.bashrc
echo 'export PYSPARK=/usr/bin/python3' >> ~/.bashrc
# Need automatic settings for spark-defaults.conf

# SCALA Settings
echo 'export SCALA_HOME=/usr/bin/sbt' >> ~/.bashrc
echo 'export PATH=$SCALA_HOME/bin:$PATH' >> ~/.bashrc

source ~/.bashrc

